#!/bin/sh
LC_ALL=C.UTF-8

mkdir -vp $HOME/log

if [ -z "`ping -w 10 -q -c1 8.8.8.8 | grep '1 received'`" ] || \
   ! curl https://stratum0.org > /dev/null 2>&1; then
	# No internet access
	exit
fi

if [ -d $HOME/Documents/Hackerspace/wiki/.git ]; then
	(
		echo
		date
		cd $HOME/Documents/Hackerspace/wiki/
		git fetch origin
	) >> $HOME/log/git-stratum0-wiki.log 2>&1
fi
