#!/bin/sh
LC_ALL=C.UTF-8

mkdir -vp $HOME/log

if [ -z "`ping -w 10 -q -c1 8.8.8.8 | grep '1 received'`" ]; then
	echo "No internet access, skipping sync" | ts >> $HOME/log/task-sync.log
	exit
fi

if [ -x "`which bugwarrior-pull`" \
     -a -r $HOME/.config/bugwarrior/bugwarriorrc \
     -a -z "$(ps -Af | grep -v grep | grep '^rohieb' | grep 'bugwarrior-pull ')" \
   ]; then
	bugwarrior-pull 2>&1 | ts >> $HOME/log/task-sync.log
fi

if [ -x "`which task`" \
     -a -r $HOME/.taskrc \
     -a -z "$(ps -Af | grep -v grep | grep '^rohieb' | grep ' task ')" \
   ]; then
	task sync 2>&1 | ts >> $HOME/log/task-sync.log
fi
